<?php

define("USER_ROLE_ADMIN", "ADMIN");

return [
    'STATUS'                    => [
        'GENRE' => [
            'M' => 'Male',
            'F' => 'Female',
            'O' => 'Other',
        ],
    ],
    'url'                       => [
        'url_source' => "https://api.thuongtamduy.com",
    ],
    'password_default' => '123456',
    'EXCEL'                     => [
        'CHAR' => [
            "",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",

            "AA",
            "AB",
            "AC",
            "AD",
            "AE",
            "AF",
            "AG",
            "AH",
            "AI",
            "AJ",
            "AK",
            "AL",
            "AM",
            "AN",
            "AO",
            "AP",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AV",
            "AW",
            "AX",
            "AY",
            "AZ",

            "BA",
            "BB",
            "BC",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BK",
            "BL",
            "BM",
            "BN",
            "BO",
            "BP",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BU",
            "BV",
            "BW",
            "BX",
            "BY",
            "BZ",

            "CA",
            "CB",
            "CC",
            "CD",
            "CE",
            "CF",
            "CG",
            "CH",
            "CI",
            "CJ",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CP",
            "CQ",
            "CR",
            "CS",
            "CT",
            "CU",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
        ],
    ],

    // Foreign Tables
    'FT'                        => [
        'users'             => [
            'profiles.user_id'       => 'Profile',
            'user_companies.user_id' => 'User Company',
            'kpi_users.user_id'      => 'Kpi User',
        ],
        'states'            => ['companies.state_id' => 'Company'],
        'countries'         => ['companies.country_id' => 'Company', 'states.country_id' => 'State'],
        'currencies'        => ['companies.currency_id' => 'Company'],
        'permission_groups' => ['permissions.group_id' => 'Permission'],
        'permissions'       => ['role_permissions.permission_id' => 'Role Permission'],
        'roles'             => ['role_permissions.role_id' => 'Role Permission'],
    ],
];
